### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by RandomAltThing** [peacestorm/ModPE-scripts#2]
I can't find the solution to the following error:
 Desktop version
org.mozilla.javascript.EvaluatorException: missing ; before statement (File.js#229)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(Unknown Source)
	at org.mozilla.javascript.DefaultErrorReporter.error(Unknown Source)
	at org.mozilla.javascript.Parser.addError(Unknown Source)
	at org.mozilla.javascript.Parser.addError(Unknown Source)
	at org.mozilla.javascript.Parser.reportError(Unknown Source)
	at org.mozilla.javascript.Parser.reportError(Unknown Source)
	at org.mozilla.javascript.Parser.reportError(Unknown Source)
	at org.mozilla.javascript.Parser.autoInsertSemicolon(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.parseFunctionBody(Unknown Source)
	at org.mozilla.javascript.Parser.function(Unknown Source)
	at org.mozilla.javascript.Parser.parse(Unknown Source)
	at org.mozilla.javascript.Parser.parse(Unknown Source)
	at org.mozilla.javascript.Context.compileImpl(Unknown Source)
	at org.mozilla.javascript.Context.compileReader(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:165)
	at java.lang.Thread.run(Thread.java:856)

**Comment by peacestorm** [comment]
Hmm...

**Comment by peacestorm** [comment]
Can you test it again? I have fixed an error.

**Comment by RandomAltThing** [comment]
Ok

**Comment by RandomAltThing** [comment]
Can you please commit the changes.

**Comment by peacestorm** [comment]
I've done that already.

**Comment by RandomAltThing** [comment]
I would if I could, but I can't so I Shant.

				                  });
org.mozilla.javascript.EvaluatorException: 'try' without 'catch' or 'finally' (AgamerR is A Dildo.js#156)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(Unknown Source)
	at org.mozilla.javascript.DefaultErrorReporter.error(Unknown Source)
	at org.mozilla.javascript.Parser.addError(Unknown Source)
	at org.mozilla.javascript.Parser.addError(Unknown Source)
	at org.mozilla.javascript.Parser.reportError(Unknown Source)
	at org.mozilla.javascript.Parser.reportError(Unknown Source)
	at org.mozilla.javascript.Parser.mustMatchToken(Unknown Source)
	at org.mozilla.javascript.Parser.mustMatchToken(Unknown Source)
	at org.mozilla.javascript.Parser.tryStatement(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.parseFunctionBody(Unknown Source)
	at org.mozilla.javascript.Parser.function(Unknown Source)
	at org.mozilla.javascript.Parser.primaryExpr(Unknown Source)
	at org.mozilla.javascript.Parser.memberExpr(Unknown Source)
	at org.mozilla.javascript.Parser.unaryExpr(Unknown Source)
	at org.mozilla.javascript.Parser.mulExpr(Unknown Source)
	at org.mozilla.javascript.Parser.addExpr(Unknown Source)
	at org.mozilla.javascript.Parser.shiftExpr(Unknown Source)
	at org.mozilla.javascript.Parser.relExpr(Unknown Source)
	at org.mozilla.javascript.Parser.eqExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitAndExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitXorExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitOrExpr(Unknown Source)
	at org.mozilla.javascript.Parser.andExpr(Unknown Source)
	at org.mozilla.javascript.Parser.orExpr(Unknown Source)
	at org.mozilla.javascript.Parser.condExpr(Unknown Source)
	at org.mozilla.javascript.Parser.assignExpr(Unknown Source)
	at org.mozilla.javascript.Parser.plainProperty(Unknown Source)
	at org.mozilla.javascript.Parser.objectLiteral(Unknown Source)
	at org.mozilla.javascript.Parser.memberExpr(Unknown Source)
	at org.mozilla.javascript.Parser.unaryExpr(Unknown Source)
	at org.mozilla.javascript.Parser.mulExpr(Unknown Source)
	at org.mozilla.javascript.Parser.addExpr(Unknown Source)
	at org.mozilla.javascript.Parser.shiftExpr(Unknown Source)
	at org.mozilla.javascript.Parser.relExpr(Unknown Source)
	at org.mozilla.javascript.Parser.eqExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitAndExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitXorExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitOrExpr(Unknown Source)
	at org.mozilla.javascript.Parser.andExpr(Unknown Source)
	at org.mozilla.javascript.Parser.orExpr(Unknown Source)
	at org.mozilla.javascript.Parser.condExpr(Unknown Source)
	at org.mozilla.javascript.Parser.assignExpr(Unknown Source)
	at org.mozilla.javascript.Parser.argumentList(Unknown Source)
	at org.mozilla.javascript.Parser.memberExprTail(Unknown Source)
	at org.mozilla.javascript.Parser.memberExpr(Unknown Source)
	at org.mozilla.javascript.Parser.unaryExpr(Unknown Source)
	at org.mozilla.javascript.Parser.mulExpr(Unknown Source)
	at org.mozilla.javascript.Parser.addExpr(Unknown Source)
	at org.mozilla.javascript.Parser.shiftExpr(Unknown Source)
	at org.mozilla.javascript.Parser.relExpr(Unknown Source)
	at org.mozilla.javascript.Parser.eqExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitAndExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitXorExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitOrExpr(Unknown Source)
	at org.mozilla.javascript.Parser.andExpr(Unknown Source)
	at org.mozilla.javascript.Parser.orExpr(Unknown Source)
	at org.mozilla.javascript.Parser.condExpr(Unknown Source)
	at org.mozilla.javascript.Parser.assignExpr(Unknown Source)
	at org.mozilla.javascript.Parser.expr(Unknown Source)
	at org.mozilla.javascript.Parser.nameOrLabel(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.statements(Unknown Source)
	at org.mozilla.javascript.Parser.block(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.ifStatement(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.parseFunctionBody(Unknown Source)
	at org.mozilla.javascript.Parser.function(Unknown Source)
	at org.mozilla.javascript.Parser.parse(Unknown Source)
	at org.mozilla.javascript.Parser.parse(Unknown Source)
	at org.mozilla.javascript.Context.compileImpl(Unknown Source)
	at org.mozilla.javascript.Context.compileReader(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:165)
	at java.lang.Thread.run(Thread.java:856)

**Comment by RandomAltThing** [comment]
Just a quick question: what version is Generic Launcher for?

**Comment by peacestorm** [comment]
0.10.something

**Comment by peacestorm** [comment]
Does it work now? I've fixed another thing.

**Comment by RandomAltThing** [comment]
Oh fuck ModPE
 Desktop version
org.mozilla.javascript.EvaluatorException: missing ; before statement (File.js#258)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(Unknown Source)
	at org.mozilla.javascript.DefaultErrorReporter.error(Unknown Source)
	at org.mozilla.javascript.Parser.addError(Unknown Source)
	at org.mozilla.javascript.Parser.addError(Unknown Source)
	at org.mozilla.javascript.Parser.reportError(Unknown Source)
	at org.mozilla.javascript.Parser.reportError(Unknown Source)
	at org.mozilla.javascript.Parser.reportError(Unknown Source)
	at org.mozilla.javascript.Parser.autoInsertSemicolon(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.parseFunctionBody(Unknown Source)
	at org.mozilla.javascript.Parser.function(Unknown Source)
	at org.mozilla.javascript.Parser.parse(Unknown Source)
	at org.mozilla.javascript.Parser.parse(Unknown Source)
	at org.mozilla.javascript.Context.compileImpl(Unknown Source)
	at org.mozilla.javascript.Context.compileReader(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:165)
	at java.lang.Thread.run(Thread.java:856)
